config/routes.rb
CaixaEletronico::Application.routes.draw do

  devise_for :clientes, controllers: {registrations: 'registrations'}

  root "caixa#index"
  get "caixa/index"

  get "contas/index"
  get "contas/show"
  get "contas/new"
  get "contas/edit"
  get "contas/create"
  get "contas/update"
  get "contas/destroy"

  get "movimentacoes/index"
  get "movimentacoes/show"
  get "movimentacoes/new"
  get "movimentacoes/edit"
  get "movimentacoes/create"
  get "movimentacoes/update"
  get "movimentacoes/destroy"

  resources :clientes do
    resources :contas do
      get "extrato/show"
      patch "extrato/show"
      get "saldo/show"
      resources :movimentacoes
    end
  end

  resources :movimentacoes, :only => [:new, :create, :show]

  get "*any", via: :all, to: "caixa#not_found"

  

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
				 :registerable,
         :recoverable,
				 :rememberable,
				 :trackable,
				 :validatable
	has_many :contas
	validates :nome, 
				presence: true, 
				length: {minimum: 10}
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
	before_action :authenticate_cliente!, except: [:new, :create]
	before_filter :validate_user, only: [:show]

	def index
		redirect_to root_path
	end

	def edit
		@cliente = Cliente.find(params[:id])
	end

	def show
		@cliente = Cliente.find(params[:id])
	end

	def new
		@cliente = Cliente.new
	end

	def create
		@cliente = Cliente.new cliente_params
		if @cliente.save
			flash[:notice] = 'Cliente criado!'
			redirect_to clientes_url
		else
			render :new
		end
	end

	def update
		@cliente = Cliente.find(params[:id])
		if @cliente.update(cliente_params)
			flash[:notice] = 'Cliente atualizada!'
			redirect_to cliente_path(@cliente)
		else
			flash[:error] = 'Conta não atualizada!'
			render :edit
		end
	end

	def destroy
		@cliente = Cliente.find(params[:id])
		@cliente.destroy
		flash[:success] = 'Cliente excluído.'
		redirect_to clientes_url
	end

	private
	def cliente_params
		params.require(:cliente).permit(:nome, :endereco, :telefone, :dataNascimento, :email, :password, :password_confirmation)
	end

	def validate_user
			unless current_cliente and current_cliente.id.to_s == params[:id]
			  reset_session
				redirect_to root_path
			end
	end
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
    <% if @cliente.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

          <ul>
            <% @cliente.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :nome %><br>
      <%= f.text_field :nome %>
    </div>
    <div class="field">
      <%= f.label :endereco, "Endereço" %><br>
      <%= f.text_field :endereco %>
    </div>
    <div class="field">
      <%= f.label :telefone %><br>
      <%= f.text_field :telefone %>
    </div>
    <div>
      <%= f.label :dataNascimento, "Data de nascimento" %>
    </div>
    <div id='datetimepicker'>
      <%= f.date_select :dataNascimento,
                        :order => [:day, :month, :year],
                        :start_year => Date.current.year, :end_year => 1920,
                        prompt: { day: 'Dia', month: 'Mês', year: 'Ano' }%>
    </div>

    <div class="field" style="padding-top: 10px;">
      <%= f.submit 'Salvar'%>
    </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editando dados do cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', @cliente %><!-- | <%= link_to 'Back', clientes_path %>-->

app/views/clientes/index.html.erb
<!--
<h1>Clientes</h1>

<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Endereço</th>
    <th>Telefone</th>
    <th>Data de nascimento</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.dataNascimento %></td>
        <td><%= link_to 'Exibir', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Excluir', cliente, method: :delete,
                        data: { confirm: 'Você tem certeza que deseja excluir o cadastro de'+cliente.nome+'?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Cliente', new_cliente_path %>-->

app/views/clientes/new.html.erb
<%= render '/shared/cliente_new' %>

app/views/clientes/show.html.erb
<div aria-hidden="false" style="background: #ccc url('/assets/banco-familia.jpg') no-repeat top;
         background-size: cover; min-height:358px; max-height:716px">
    <div style="margin-top: 5%; padding: 5%">
      <div >
        <h1 style="color:false">
          <strong>Bem Vindo!</strong>
        </h1>
      </div>
      <h2 style="color:false">Trabalhamos por você.</h2>
    </div>
</div>