config/routes.rb
CaixaEletronico::Application.routes.draw do

  devise_for :clientes, controllers: {registrations: 'registrations'}

  root "caixa#index"
  get "caixa/index"

  get "contas/index"
  get "contas/show"
  get "contas/new"
  get "contas/edit"
  get "contas/create"
  get "contas/update"
  get "contas/destroy"

  get "movimentacoes/index"
  get "movimentacoes/show"
  get "movimentacoes/new"
  get "movimentacoes/edit"
  get "movimentacoes/create"
  get "movimentacoes/update"
  get "movimentacoes/destroy"

  resources :clientes do
    resources :contas do
      get "extrato/show"
      patch "extrato/show"
      get "saldo/show"
      resources :movimentacoes
    end
  end

  resources :movimentacoes, :only => [:new, :create, :show]

  get "*any", via: :all, to: "caixa#not_found"

  

end

app/models/conta.rb
class Conta < ActiveRecord::Base
  belongs_to :cliente
  has_many :origens, :class_name => 'Movimentacao', :foreign_key => 'conta_orig_id'
  has_many :destinos, :class_name => 'Movimentacao', :foreign_key => 'conta_dest_id'

  validates :codigo, presence: true,
            length: {is: 5}, uniqueness: true, numericality: { only_integer: true }
  validates :cliente_id, presence: true


  def saldo
    saldo = 0
    movimentacoes = (self.origens << self.destinos).sort{|a,b| a.created_at <=> b.created_at }

    movimentacoes.each do |movimentacao|
      if  (['T'].include? movimentacao.tipo)
        if self.id == movimentacao.conta_dest_id
          saldo += movimentacao.valor
        else
          saldo -= movimentacao.valor
        end
      end

      if  (['S'].include? movimentacao.tipo)
        saldo -= movimentacao.valor
      end
      if movimentacao.tipo == 'D'
        saldo += movimentacao.valor
      end

    end
    saldo
  end


  def saldo_parcial(movimentacoes)
    saldo = 0

    movimentacoes.each do |movimentacao|
      if  (['T'].include? movimentacao.tipo)
        if self.id == movimentacao.conta_dest_id
          saldo += movimentacao.valor
        else
          saldo -= movimentacao.valor
        end
      end
      if movimentacao.tipo == 'D'
        saldo += movimentacao.valor
      end
    end
    saldo
    end

end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_action :authenticate_cliente!
  before_action :set_conta, only: [:show, :edit, :update, :destroy]

  # GET /contas
  def index
    @cliente = Cliente.find( params[:cliente_id])
    @contas = Conta.where(['cliente_id=? and ativa=?', params[:cliente_id], true])
  end

  # GET /contas/1
  def show
    @cliente = Cliente.find(params[:cliente_id])
    @conta = Conta.find(params[:id], :conditions => ["ativa=?", true])
  end

  # GET /contas/new
  def new
    @cliente = Cliente.find(params[:cliente_id])
    @conta = Conta.new
  end

  # GET /contas/1/edit
  def edit
    @cliente = Cliente.find(params[:cliente_id])
    @conta = Conta.find(params[:id], :conditions => ["ativa=?", true])
  end

  # POST /contas
  def create
    @cliente = Cliente.find(params[:cliente_id])
    @conta = Conta.new conta_params
    if @conta.save
      flash[:notice] = 'Conta criada!'
      redirect_to cliente_conta_path(@conta.cliente, @conta)
    else
      flash[:error] = 'Conta não criada!'
      render :new
    end
  end

  # PATCH/PUT /contas/1
  def update
    if @conta.update(conta_params)
      flash[:notice] = 'Conta atualizada!'
      redirect_to cliente_conta_path(@conta.cliente, @conta)
    else
      flash[:error] = 'Conta não atualizada!'
      render :edit
    end
  end

  # DELETE /contas/1
  def destroy
    @conta = Conta.find(params[:id])
    @conta.ativa = false
    if @conta.save
      flash[:notice] = 'Conta desativada!'
      redirect_to cliente_path(params[:cliente_id])
    else
      flash[:error] = 'Conta não pôde ser desativada!'
      redirect_to cliente_path(params[:cliente_id])
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_conta
    @conta = Conta.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def conta_params
    params.require(:conta).permit(:descricao, :codigo, :cliente_id)
  end

  def conta_update_params
    params.require(:conta).permit(:descricao)
  end
end

app/views/contas/_form.html.erb
<%= form_for([@cliente, @conta]) do |f| %>
    <% if @conta.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@conta.errors.count, "error") %> prohibited this conta from being saved:</h2>

          <ul>
            <% @conta.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :codigo, "Código" %><br>
      <%= f.text_field :codigo, disabled: @conta.persisted? %>
    </div>
    <div class="field">
      <%= f.label :descricao, "Descrição" %><br>
      <%= f.text_field :descricao %>
    </div>
    <%= f.hidden_field :cliente_id , :value=>params[:cliente_id] %>
    <div class="actions">
      <%= f.submit "Salvar" %>
    </div>
<% end %>

app/views/contas/edit.html.erb
<h1>Editando conta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', cliente_path(@cliente) %>

app/views/contas/index.html.erb
<fieldset>
  <legend><h3>Contas:</h3></legend>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Descrição</th>
      <th>Código</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @contas.each do |conta| %>
        <tr>
          <td><%= conta.descricao %></td>
          <td><%= conta.codigo %></td>
          <td><%= link_to 'Editar', edit_cliente_conta_path(@cliente, conta) %></td>
          <td><%= link_to 'Saldo', cliente_conta_saldo_show_path(@cliente, conta) %></td>
          <td><%= link_to 'Extrato', cliente_conta_extrato_show_path(@cliente, conta) %></td>
          <td><%= link_to 'Saque', new_cliente_conta_movimentacao_path(@cliente, conta, :tipo => 'S') %></td>
          <td><%= link_to 'Transferência', new_cliente_conta_movimentacao_path(@cliente, conta, :tipo => 'T') %></td>
          <td>
            <%= link_to 'Desativar conta?', cliente_conta_path(@cliente, conta), method: :delete,
                        data: { confirm: 'Você tem certeza que deseja desativar a conta '+conta.codigo+'?' } %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</fieldset>

app/views/contas/new.html.erb
<h1>Nova conta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', :back %>

app/views/contas/show.html.erb
<h2>Conta - <%= @conta.codigo %></h2>

<p>
  <strong>Cliente:</strong>
  <%= @conta.cliente.nome %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @conta.descricao %>
</p>

<%= link_to 'Voltar', cliente_path(@cliente) %>