config/routes.rb
CaixaEletronico::Application.routes.draw do

  devise_for :clientes, controllers: {registrations: 'registrations'}

  root "caixa#index"
  get "caixa/index"

  get "contas/index"
  get "contas/show"
  get "contas/new"
  get "contas/edit"
  get "contas/create"
  get "contas/update"
  get "contas/destroy"

  get "movimentacoes/index"
  get "movimentacoes/show"
  get "movimentacoes/new"
  get "movimentacoes/edit"
  get "movimentacoes/create"
  get "movimentacoes/update"
  get "movimentacoes/destroy"

  resources :clientes do
    resources :contas do
      get "extrato/show"
      patch "extrato/show"
      get "saldo/show"
      resources :movimentacoes
    end
  end

  resources :movimentacoes, :only => [:new, :create, :show]

  get "*any", via: :all, to: "caixa#not_found"

  

end

app/views/layouts/_content.html.erb
<div class="profile-content">
  <% if !notice.nil? %>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Informação!</strong> <%= notice %>
      </div>
  <% end %>
  <% if !alert.nil? %>
      <div class="alert alert-warning fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Alerta!</strong> <%= alert %>
      </div>
  <% end %>
  <% if !flash[:error].nil? %>
      <div class="alert alert-danger fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Atenção!</strong> <%= flash[:error] %>
      </div>
  <% end %>
  <%= yield %>
</div>

app/views/layouts/_top_menu.html.erb
<% if cliente_signed_in? %>
    <li class="dropdown">
      <a href="#" class=" dropdown-toggle" type="button" data-toggle="dropdown">
        <span class="glyphicon glyphicon-user"></span> <%= current_cliente.nome %>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li> <%= link_to edit_cliente_registration_path do %>
              <span class="glyphicon glyphicon-edit"></span> Alterar senha
          <% end %>
        </li>
        <li class="divider"></li>
        <li><%= link_to destroy_cliente_session_path, :method => 'delete' do%>
              <span class="glyphicon glyphicon-log-out"></span> Sair
          <% end %>
        </li>
      </ul>
    </li>
    <!--<li><%= link_to destroy_cliente_session_path, :method => 'delete' do%>
          <span class="glyphicon glyphicon-log-out"></span> Sair
      <% end %>
    </li>-->


<% else %>
    <li>
    <li>
      <%= link_to new_cliente_path do%>
          <span class="glyphicon glyphicon-user"></span> Cadastrar
      <% end %></li>
    </li>
<% end %>

app/views/layouts/_user_side_menu.html.erb
<div class="col-md-3">
  <div class="profile-sidebar">
    <!-- SIDEBAR USERPIC -->
    <div class="profile-userpic">
      <%= image_tag "AVATAR.png", :class =>  'img-responsive' %>
    </div>
    <!-- END SIDEBAR USERPIC -->
    <!-- SIDEBAR USER TITLE -->
    <div class="profile-usertitle">
      <div class="profile-usertitle-name">
        <%= current_cliente.nome %>
      </div>
      <div class="profile-usertitle-job">
        Cliente
      </div>
    </div>
    <!-- END SIDEBAR USER TITLE -->
    <!-- SIDEBAR BUTTONS -->
    <div class="profile-userbuttons">

      <%= link_to new_cliente_conta_path(@cliente.id), :class => "btn btn-success", :style => 'color: #FFFFFF',
                  :role => "button" do %>
          <span class="glyphicon glyphicon-plus-sign"></span>
          Conta
      <% end %>

      <%= link_to @cliente, method: :delete,:class => "btn btn-danger btn-sm",:style => 'color: #FFFFFF',
                  data: { confirm: 'Você tem certeza que deseja excluir o cadastro de "'+@cliente.nome+'"?' } do %>
          <span class="glyphicon glyphicon-minus-sign"></span> Cliente
      <% end %>

    </div>
    <!-- END SIDEBAR BUTTONS -->
    <!-- SIDEBAR MENU -->
    <div class="profile-usermenu">
      <ul class="nav">
        <li>

          <%= link_to cliente_path(@cliente) do%>
              <i class="glyphicon glyphicon-home"></i>
              Início
          <% end %>
        </li>
        <li>
          <%= link_to edit_cliente_path(@cliente) do%>
              <i class="glyphicon glyphicon-user"></i>
              Editar dados
          <% end %>
        </li>
        <li>

          <%= link_to cliente_contas_path(@cliente) do%>
              <i class="glyphicon glyphicon-usd"></i>
             Contas - Operações
          <% end %>

        </li>
        <li>
          <%= link_to destroy_cliente_session_path, :method => 'delete' do%>
              <span class="glyphicon glyphicon-log-out"></span> Sair
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caixa Eletrônico</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="/assets/ruby.ico"></head>
<body>
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Banco RoR", root_path, :class => "navbar-brand" %> #
    </div>
    <ul class="nav navbar-nav navbar-right">
      <%= render 'layouts/top_menu' %>
      <% if !cliente_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"></span> Entrar</a>
            <ul id="login-dp" class="dropdown-menu">
              <li>
                <div class="row">
                  <div class="col-md-12">
                    <%= render '/clientes/sessions/login' %>
                  </div>
                </div>
              </li>
            </ul>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="row profile">
    <% if cliente_signed_in? %>
      <%= render "layouts/user_side_menu" %>
    <% end %>
    <div class="<%= cliente_signed_in? ? 'col-md-9' : 'col-md-12' %>">
     <%= render "layouts/content" %>
    </div>
  </div>
</div>
</body>

</html>